name: ccloud-service-broker
version: 0.0.1
id: faebbe18-0a84-11e9-ab14-d663bd873d94
description: "A service broker in WIP."
displayName: "CCloud Service Broker"

tags: test
labels:
  showcase: "true"
providerDisplayName: SAP
longDescription: "CCloud Service Broker in WIP"
bindable: false
planUpdatable: true
