# Use this yaml file to register namespace-scoped UPS Broker
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBroker
metadata:
  name:  {{ template "fullname" . }}
spec:
  url: http://{{ template "fullname" . }}."{{ .Release.Namespace }}".svc.cluster.local